server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 10.249.175.123:8848
oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  keyid:  #填写刚刚生成的AccessKey
  keysecret:   # 填写刚刚生成的Accesssecret
  bucketname: edu-wenhao # bucket名称
  filehost: avatar    #bucket下文件夹的路径
